"""
=============================================================================
DL PIPELINE CONFIGURATION
=============================================================================

Central configuration module for the YOLOv8 skin lesion segmentation pipeline.
All hyper-parameters, file paths, class definitions, and hardware settings
live here so that every other module imports from a single source of truth.

Typical usage
-------------
    from dl_pipeline.config import (
        DATASET_PATH, TRAIN_PATH, MODEL_SIZE,
        CLASS_NAMES, CLASS_SEVERITY, get_device
    )

Sections
--------
1. Dataset Paths          – root directory and split sub-paths
2. Class Definitions      – lesion codes, full names, and severity levels
3. YOLOv8 Model Settings  – model variant selection
4. Training Hyperparams   – epochs, batch size, LR, augmentation, etc.
5. GPU Settings           – auto-detect CUDA and expose a helper
6. Visualization Settings – per-class BGR colours and inference thresholds
7. Misc                   – file extensions, random seed
8. Helper Functions       – directory creation, path helpers, config printer
"""

import os
from typing import Dict, List, Tuple

import torch

# ============================================================================
# DATASET PATHS
# ============================================================================

# Absolute path to the root of the YOLO-formatted skin-lesion dataset.
# Expected layout:
#   <DATASET_PATH>/
#       train/images/   train/labels/
#       valid/images/   valid/labels/
#       test/images/    test/labels/
#       data.yaml       (generated by step1_prepare_data.py)
DATASET_PATH: str = os.path.join(os.path.dirname(os.path.dirname(__file__)), "skin-lesion-segmentation-classification")

# Paths to each data split (constructed from DATASET_PATH)
TRAIN_PATH: str = os.path.join(DATASET_PATH, "train")
VALID_PATH: str = os.path.join(DATASET_PATH, "valid")
TEST_PATH:  str = os.path.join(DATASET_PATH, "test")

# Directory where all pipeline artefacts (models, plots, JSON results) are saved.
# Resolved relative to this config file so it works regardless of the CWD.
OUTPUT_DIR: str = os.path.join(os.path.dirname(__file__), "results")


# ============================================================================
# CLASS DEFINITIONS (Skin Lesion Types)
# ============================================================================

# Short three/four-letter diagnostic code for each YOLO class index.
# These codes are written into data.yaml and appear in inference JSON output.
CLASS_CODES: Dict[int, str] = {
    0: "BKL",    # Benign Keratosis
    1: "NV",     # Melanocytic Nevi
    2: "DF",     # Dermatofibroma
    3: "MEL",    # Melanoma
    4: "VASC",   # Vascular Lesion
    5: "BCC",    # Basal Cell Carcinoma
    6: "AKIEC",  # Actinic Keratoses / Intraepithelial Carcinoma
}

# Human-readable full name for each class index.
# Used in visualizations and log messages.
CLASS_NAMES: Dict[int, str] = {
    0: "Benign Keratosis",
    1: "Melanocytic Nevi",
    2: "Dermatofibroma",
    3: "Melanoma",
    4: "Vascular Lesion",
    5: "Basal Cell Carcinoma",
    6: "Actinic Keratoses",
}

# Severity level for each class:
#   0 = Benign        (no immediate concern)
#   1 = Pre-cancerous (requires monitoring)
#   2 = Malignant     (urgent clinical review)
# step4_inference.py uses this to colour-code and label detections.
CLASS_SEVERITY: Dict[int, int] = {
    0: 0,  # BKL   – Benign
    1: 0,  # NV    – Benign
    2: 0,  # DF    – Benign
    3: 2,  # MEL   – Malignant  ⚠  (CRITICAL)
    4: 0,  # VASC  – Benign
    5: 2,  # BCC   – Malignant  ⚠
    6: 1,  # AKIEC – Pre-cancerous
}

# Total number of classes; derived automatically so it stays in sync.
NUM_CLASSES: int = len(CLASS_CODES)


# ============================================================================
# YOLOV8 MODEL SETTINGS
# ============================================================================

# Model size suffix: 'n' (nano) | 's' (small) | 'm' (medium) | 'l' (large) | 'x' (xlarge).
# Larger models are more accurate but require more GPU memory and training time.
# Recommended for RTX 5050 8 GB: 'n' or 's'
MODEL_SIZE: str = 'n'

# Full pre-trained model filename used by step2_train.py.
# Ultralytics will download this automatically on first run if not cached.
MODEL_NAME: str = f"yolov8{MODEL_SIZE}-seg.pt"


# ============================================================================
# TRAINING HYPERPARAMETERS
# ============================================================================

# Total training epochs.
# Quick test: 2–5  |  Normal: 50–100  |  Full: 100–300
EPOCHS: int = 50

# Images per gradient-update step.
# Reduce if the GPU runs out of memory (OOM errors).
# RTX 5050 8 GB sweet-spot: 8–16
BATCH_SIZE: int = 8

# Pixel width/height fed into the network (must be divisible by 32).
IMAGE_SIZE: int = 640

# Initial learning rate for the SGD/Adam optimiser.
# YOLO's built-in cosine-decay schedule adjusts this during training.
LEARNING_RATE: float = 0.01

# L2 weight-decay coefficient; regularises the model to prevent overfitting.
WEIGHT_DECAY: float = 0.0005

# Early-stopping patience: training halts if the validation metric does not
# improve for this many consecutive epochs.
PATIENCE: int = 10

# Parallel data-loading workers; increase for faster I/O on multi-core CPUs.
WORKERS: int = 4


# ============================================================================
# GPU SETTINGS
# ============================================================================

def get_device() -> str:
    """
    Detect the best available compute device and print a status message.

    Checks for a CUDA-capable GPU via ``torch.cuda.is_available()``.
    If one is found, prints its name and total VRAM; otherwise falls back
    to the CPU with a performance warning.

    Returns
    -------
    str
        ``'cuda'`` when a GPU is available, ``'cpu'`` otherwise.
    """
    if torch.cuda.is_available():
        device = 'cuda'
        gpu_name = torch.cuda.get_device_name(0)
        gpu_mem  = torch.cuda.get_device_properties(0).total_memory / 1e9
        print(f"✅ GPU detected: {gpu_name} ({gpu_mem:.1f} GB)")
    else:
        device = 'cpu'
        print("⚠️ No GPU detected, using CPU (training will be slow)")
    return device


# Module-level device string; imported directly when a function call is not needed.
DEVICE: str = 'cuda' if torch.cuda.is_available() else 'cpu'


# ============================================================================
# VISUALIZATION SETTINGS
# ============================================================================

# Per-class overlay colours in BGR format (as expected by OpenCV).
# Danger classes (MEL, BCC) use red/orange to communicate risk visually.
CLASS_COLORS: List[Tuple[int, int, int]] = [
    (255, 100, 100),   # Light Blue  – BKL
    (100, 255, 100),   # Light Green – NV
    (100, 100, 255),   # Light Red   – DF
    (0,   0,   255),   # Red         – MEL  ⚠ (highest danger)
    (255, 200, 100),   # Cyan        – VASC
    (0,   100, 255),   # Orange      – BCC  ⚠
    (200, 100, 255),   # Pink        – AKIEC
]

# Minimum detection confidence kept after NMS.
# Lower values surface more candidates but increase false positives.
CONF_THRESHOLD: float = 0.25

# Intersection-over-Union threshold for Non-Maximum Suppression.
# Detections that overlap more than this fraction are deduplicated.
IOU_THRESHOLD: float = 0.45


# ============================================================================
# SUPPORTED FILE EXTENSIONS
# ============================================================================

# Image formats accepted by the pipeline's directory scanners.
IMAGE_EXTENSIONS: List[str] = [".jpg", ".jpeg", ".png", ".bmp", ".webp"]


# ============================================================================
# RANDOM SEED (for reproducibility)
# ============================================================================

# Fixed seed passed to Python's ``random`` module and NumPy so that
# sample selection and shuffles are deterministic across runs.
RANDOM_SEED: int = 42


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def ensure_output_dir() -> str:
    """
    Create the output directory (and any missing parent directories) if absent.

    This is called automatically when ``config`` is imported, so downstream
    modules can write artefacts without performing their own ``os.makedirs``.

    Returns
    -------
    str
        Absolute path to ``OUTPUT_DIR``.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    return OUTPUT_DIR


def get_data_yaml_path() -> str:
    """
    Build the expected path to the ``data.yaml`` configuration file.

    ``data.yaml`` is generated by ``step1_prepare_data.py`` and consumed by
    YOLOv8's training, validation, and inference routines.

    Returns
    -------
    str
        Absolute path to ``<DATASET_PATH>/data.yaml``.
    """
    return os.path.join(DATASET_PATH, "data.yaml")


def print_config() -> None:
    """
    Print a formatted summary of the current pipeline configuration to stdout.

    Useful for verifying settings before a long training run.
    Covers dataset path, model variant, class count, key hyperparameters,
    compute device, and output directory.
    """
    print("\n" + "=" * 60)
    print("DL PIPELINE CONFIGURATION")
    print("=" * 60)
    print(f"  Dataset: {DATASET_PATH}")
    print(f"  Model: YOLOv8{MODEL_SIZE}-seg")
    print(f"  Classes: {NUM_CLASSES}")
    print(f"  Epochs: {EPOCHS}")
    print(f"  Batch Size: {BATCH_SIZE}")
    print(f"  Image Size: {IMAGE_SIZE}x{IMAGE_SIZE}")
    print(f"  Device: {DEVICE}")
    print(f"  Output: {OUTPUT_DIR}")
    print("=" * 60 + "\n")


# Ensure the output directory is ready as soon as this module is imported.
ensure_output_dir()
