"""
=============================================================================
STEP 1: PREPARE DATA FOR YOLOV8
=============================================================================

Generate the ``data.yaml`` configuration file that YOLOv8 requires before
training.  This file tells the framework where the dataset lives and what
classes are present.

What this module does
---------------------
1. ``create_data_yaml`` – write a fully-annotated ``data.yaml`` to
   ``<DATASET_PATH>/data.yaml`` containing dataset root path, relative
   split paths, class count, and class name mapping.
2. ``validate_labels``   – spot-check up to 10 training label files to
   confirm they follow the YOLO segmentation format
   (``class_id x1 y1 x2 y2 …``).

Generated ``data.yaml`` structure
----------------------------------
::

    path: <DATASET_PATH>
    train: train/images
    val:   valid/images
    test:  test/images

    nc: 7

    names:
      0: BKL   # Benign Keratosis
      1: NV    # Melanocytic Nevi
      …

Command-line usage
------------------
    python step1_prepare_data.py
"""

import os
import sys
import glob
from typing import Optional

# Make the parent package importable when this file is run directly.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dl_pipeline.config import (
    DATASET_PATH, TRAIN_PATH, VALID_PATH, TEST_PATH,
    CLASS_NAMES, CLASS_CODES, NUM_CLASSES,
    get_data_yaml_path
)


# ============================================================================
# DATA PREPARATION FUNCTIONS
# ============================================================================

def create_data_yaml() -> str:
    """
    Write the ``data.yaml`` configuration file for YOLOv8 training.

    The file is placed at ``<DATASET_PATH>/data.yaml`` and specifies:

    * **path**  – absolute root directory of the dataset.
    * **train / val / test** – relative sub-paths to each image split.
    * **nc**    – number of classes (derived from ``config.NUM_CLASSES``).
    * **names** – class-index → short-code mapping (e.g. ``0: BKL``),
      with the full name appended as a YAML comment.

    Any existing ``data.yaml`` is silently overwritten, making this step
    safe to re-run after changing class definitions.

    Returns
    -------
    str
        Absolute path to the newly created ``data.yaml`` file.
    """
    print("\n" + "╔" + "═" * 58 + "╗")
    print("║" + " STEP 1: PREPARE DATA FOR YOLOV8 ".center(58) + "║")
    print("╚" + "═" * 58 + "╝")

    data_yaml_path = get_data_yaml_path()

    # Build the YAML string programmatically so class definitions in
    # config.py are the single source of truth.
    yaml_content = f"""# Skin Lesion Segmentation Dataset
# Auto-generated by DL Pipeline

# Dataset root path
path: {DATASET_PATH}

# Relative paths to splits (from 'path')
train: train/images
val: valid/images
test: test/images

# Number of classes
nc: {NUM_CLASSES}

# Class names
"""

    # Append one entry per class in numeric order.
    for class_id in range(NUM_CLASSES):
        code = CLASS_CODES.get(class_id, f"class_{class_id}")
        name = CLASS_NAMES.get(class_id, f"Class {class_id}")
        yaml_content += f"  {class_id}: {code}  # {name}\n"

    # Persist to disk.
    with open(data_yaml_path, 'w') as f:
        f.write(yaml_content)

    print(f"\n  ✅ Created: {data_yaml_path}")
    print(f"\n  📄 Contents:")
    print("  " + "-" * 50)
    for line in yaml_content.split('\n'):
        print(f"  {line}")
    print("  " + "-" * 50)

    return data_yaml_path


def validate_labels() -> bool:
    """
    Spot-check up to 10 training label files for correct YOLO format.

    A label file is considered *valid* when every non-empty line:

    * Contains **at least 7 whitespace-separated tokens**
      (``class_id`` + 3 coordinate pairs = 7 tokens minimum).
    * Starts with an integer ``class_id`` in the range
      ``[0, NUM_CLASSES)``.

    Checking only a sample (rather than the full dataset) keeps this step
    fast while still catching systematic formatting errors.

    Returns
    -------
    bool
        ``True`` when the sampled labels all pass validation.
        ``False`` if no label files are found (empty labels directory).

    Notes
    -----
    Invalid individual lines within an otherwise-parseable file are flagged
    by marking the whole file as invalid, which errs on the side of caution.
    """
    print("\n  🔍 Validating label format...")

    labels_dir   = os.path.join(TRAIN_PATH, "labels")
    label_files  = glob.glob(os.path.join(labels_dir, "*.txt"))

    if not label_files:
        print("  ❌ No label files found!")
        return False

    sample_size = min(10, len(label_files))
    valid_count = 0

    for label_path in label_files[:sample_size]:
        with open(label_path, 'r') as f:
            lines = f.readlines()

        is_valid = True
        for line in lines:
            parts = line.strip().split()
            # Minimum: class_id + 3 points × 2 coords = 7 tokens.
            if len(parts) < 7:
                is_valid = False
                break

            # First token must be a valid integer class index.
            try:
                class_id = int(parts[0])
                if class_id < 0 or class_id >= NUM_CLASSES:
                    is_valid = False
            except ValueError:
                is_valid = False

        if is_valid:
            valid_count += 1

    print(f"  ✅ Validated {valid_count}/{sample_size} sample labels - format OK")
    return True


# ============================================================================
# ORCHESTRATOR
# ============================================================================

def run_prepare_data() -> str:
    """
    Orchestrate Step 1: create ``data.yaml`` then validate a label sample.

    Called by ``run_pipeline.py`` as part of the full pipeline, or
    directly via the command line.

    Returns
    -------
    str
        Absolute path to the created ``data.yaml`` file.
    """
    # Generate the YAML configuration file.
    yaml_path = create_data_yaml()

    # Sanity-check a small label sample to catch format errors early.
    validate_labels()

    print("\n" + "=" * 60)
    print("✅ STEP 1 COMPLETE!")
    print(f"   data.yaml created at: {yaml_path}")
    print("   Ready for training!")
    print("=" * 60 + "\n")

    return yaml_path


# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    run_prepare_data()
