"""
=============================================================================
STEP 1: PREPARE DATA FOR YOLOV8
=============================================================================

Create the data.yaml configuration file required by YOLOv8 for training.
This file tells YOLOv8 where your data is and what classes you have.

Usage:
    python step1_prepare_data.py
"""

import os
import sys

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dl_pipeline.config import (
    DATASET_PATH, TRAIN_PATH, VALID_PATH, TEST_PATH,
    CLASS_NAMES, CLASS_CODES, NUM_CLASSES,
    get_data_yaml_path
)


def create_data_yaml():
    """
    Create the data.yaml file for YOLOv8 training.
    
    This file specifies:
    - Path to the dataset
    - Paths to train/val/test splits
    - Number of classes
    - Class names
    """
    print("\n" + "╔" + "═" * 58 + "╗")
    print("║" + " STEP 1: PREPARE DATA FOR YOLOV8 ".center(58) + "║")
    print("╚" + "═" * 58 + "╝")
    
    data_yaml_path = get_data_yaml_path()
    
    # Build yaml content
    yaml_content = f"""# Skin Lesion Segmentation Dataset
# Auto-generated by DL Pipeline

# Dataset root path
path: {DATASET_PATH}

# Relative paths to splits (from 'path')
train: train/images
val: valid/images
test: test/images

# Number of classes
nc: {NUM_CLASSES}

# Class names
names:
"""
    
    # Add class names
    for class_id in range(NUM_CLASSES):
        code = CLASS_CODES.get(class_id, f"class_{class_id}")
        name = CLASS_NAMES.get(class_id, f"Class {class_id}")
        yaml_content += f"  {class_id}: {code}  # {name}\n"
    
    # Write the file
    with open(data_yaml_path, 'w') as f:
        f.write(yaml_content)
    
    print(f"\n  ✅ Created: {data_yaml_path}")
    print(f"\n  📄 Contents:")
    print("  " + "-" * 50)
    for line in yaml_content.split('\n'):
        print(f"  {line}")
    print("  " + "-" * 50)
    
    return data_yaml_path


def validate_labels():
    """Validate that label files are in correct YOLO format."""
    print("\n  🔍 Validating label format...")
    
    import glob
    labels_dir = os.path.join(TRAIN_PATH, "labels")
    label_files = glob.glob(os.path.join(labels_dir, "*.txt"))
    
    if not label_files:
        print("  ❌ No label files found!")
        return False
    
    # Check a sample of labels
    sample_size = min(10, len(label_files))
    valid_count = 0
    
    for label_path in label_files[:sample_size]:
        with open(label_path, 'r') as f:
            lines = f.readlines()
        
        is_valid = True
        for line in lines:
            parts = line.strip().split()
            if len(parts) < 7:  # class_id + at least 3 points (6 coords)
                is_valid = False
                break
            
            # Check if first part is integer (class_id)
            try:
                class_id = int(parts[0])
                if class_id < 0 or class_id >= NUM_CLASSES:
                    is_valid = False
            except ValueError:
                is_valid = False
        
        if is_valid:
            valid_count += 1
    
    print(f"  ✅ Validated {valid_count}/{sample_size} sample labels - format OK")
    return True


def run_prepare_data():
    """Run data preparation."""
    # Create data.yaml
    yaml_path = create_data_yaml()
    
    # Validate labels
    validate_labels()
    
    print("\n" + "=" * 60)
    print("✅ STEP 1 COMPLETE!")
    print(f"   data.yaml created at: {yaml_path}")
    print("   Ready for training!")
    print("=" * 60 + "\n")
    
    return yaml_path


# ============================================================================
# ENTRY POINT
# ============================================================================

if __name__ == "__main__":
    run_prepare_data()
